### ISSUE TITLE
Remote Debugging for other platforms

### ISSUE THREAD

**Issue by jethron** [poplindata/chrome-snowplow-inspector#26]
Extension already seems to work OK using the built-in [Remote Debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/) feature in DevTools, in this way you can test on (Android) mobile devices, but only for apps that support it (pretty much Chrome, but potentially [other WebViews](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/webviews)). But this doesn't help for native apps or trackers on other platforms.

So we basically want some way to intercept arbitrary traffic (ala [mitmproxy](https://mitmproxy.org/)/[Fiddler](https://www.telerik.com/fiddler)/[Charles](https://www.charlesproxy.com/)) to sniff the requests.

For a first round, it looks like Charles at least can export an entire session as a HAR file. Since this is the same format Chrome gives us we already can parse that, so we just need an import capability.

But a real-time solution would be better, though I suspect much harder.

**Comment by miike** [comment]
@jethron Do we close this now that we have the universal tunnel support?

**Comment by jethron** [comment]
Yeah, between HAR import remote debugging and the ngrok tunnel I think most bases are covered.
