### ISSUE TITLE
Add support for custom Snowplow paths

### ISSUE THREAD

**Issue by miike** [poplindata/chrome-snowplow-inspector#34]
Currently supports /i and /tp2 but inflexibly supports other paths (if they have tv in them). Consider adding regex support for other paths in options.

**Comment by jethron** [comment]
Custom paths are only really supported for POST requests out of the box. At the moment if the post request doesn't match the `/tp2` check, it inspects the post body for `data` and `schema` properties to see if the schema is an Iglu URI containing `payload_data`. So it's already pretty generic I think. Is there a usecase for custom get paths? Example page where the plugin doesn't detect the beacons correctly?

Side note: don't think we track going through the collector for redirect events; that might be worth adding separately; though might not be fully accurate when custom paths come into play.

**Comment by miike** [comment]
It's possible to customise the GET path but I haven't seen it done much - if we're picking it up based on the post body that should be fine.

For redirects we can probably leave that for the moment?
