### ISSUE TITLE
Support GA Beacons Sent from snowplow-google-analytics-plugin

### ISSUE THREAD

**Issue by jethron** [poplindata/chrome-snowplow-inspector#41]
https://github.com/snowplow-incubator/snowplow-google-analytics-plugin

This will involve parsing the Measurement Protocol + GA-specific extensions.

TODO: Decide if we should show regular GA beacons as well? An argument can be made that it's useful for ensuring tracking parity between systems. They would need to be filterable easily..

**Comment by miike** [comment]
I like this idea - let's go with intercepting the Snowplow / google.analytics/v1 requests for the moment and then figure out the effort involved in looking at the GA beacons.
