### ISSUE TITLE
Extension spams permission requests on Chrome

### ISSUE THREAD

**Issue by Guillaume1414** [poplindata/chrome-snowplow-inspector#42]
Every time I load a page I get 10+ popups saying "Snowplow Inspector has requested additional permissions". 

There needs to be a way to turn this off.

**Comment by jethron** [comment]
Thanks @Guillaume1414 for your feedback, and apologies for the inconvenience this has caused you. v0.2.19 has just been submitted for review which should very much alleviate this issue and make the permissions work in other browsers like Edge that will only prompt once you actually interact with the extension (via a click within the actual extension). After that you should only get prompted once trying to connect to a new Iglu repository for the first time.

Hopefully this will resolve this issue for you, if not, please feel free to reopen this issue.

Thanks again for the feedback!
