### ISSUE TITLE
Extension options iframe not working

### ISSUE THREAD

**Issue by sandra0503** [poplindata/chrome-snowplow-inspector#43]
For some reason the options dialogue does not work for me (version Chrome 96). I can see there is an iframe which doesn't load for me.
Is there any other way to add custom Iglu repositories?

<img width="768" alt="Screenshot 2021-12-17 at 15 08 05" src="https://user-images.githubusercontent.com/2573547/146565086-17444161-af8b-4141-bdd0-f7f78119ed6a.png">

**Comment by jethron** [comment]
Hey @sandra0503 , apologies for the delay.

Custom repositories should now be managed within the extension itself, if you hit the 'Manage Schemas' button, then give it a moment to load, then hit 'Registries...', then 'Add' and fill out the details there.

The options should mostly just consist now of the anonymous data opt-out, but if that's missing that's a worry. Can you share your Chrome version and Operating System so I can try to replicate this issue?

**Comment by miike** [comment]
@sandra0503 Did you manage to resolve this issue?
