### ISSUE TITLE
UTF-8 Encoding

### ISSUE THREAD

**Issue by k-s-710** [poplindata/chrome-snowplow-inspector#60]
Could we update to use UTF-8 or have the option? Our french characters show encoded which cause people to think they are captured that way. However our database shows them correctly.

**Comment by miike** [comment]
Hi @k-s-710 are you able to include a screenshot or URL that we can test on to recreate? Thanks.

**Comment by k-s-710** [comment]
Sure, when searching for épinard we capture the search term and it shows like so in the debugger
![Screen Shot 2022-10-07 at 11 00 09 AM](https://user-images.githubusercontent.com/115262156/194585299-34c81a90-7136-438a-89fe-49c8485da81c.png)

**Comment by k-s-710** [comment]
confirmed that the charset is utf-8 in the source. I also confirmed in the payloads in the network tab that we are sending "épinard" and not an encoded value.

**Comment by jethron** [comment]
This looks like a bug where after decoding a base64 payload (context/unstruct) we weren't decoding the payload as utf8 before parsing the JSON. Should be fixed in the next version.

Thanks for your report @k-s-710!
