### ISSUE TITLE
Import options incorrect

### ISSUE THREAD

**Issue by k-s-710** [poplindata/chrome-snowplow-inspector#69]
When I click "Import" the "HAR File" is already checked. If I click on "HAR file" it does nothing, however if I click "Bad Rows" my file explorer pops up and allows me to import an HAR file. If I click "ElasticSearch" I get the pop up of the "Bad Rows Import". If I click the "Ngrok Tunnel" option, the elastic search option pops up.

**Comment by k-s-710** [comment]
It also seems that nothing shows if I use the bad rows import and paste the _source JSON property from ElasticSearch.

**Comment by jethron** [comment]
Thanks for the report @k-s-710 !

I'm not able to replicate the issue with the Import menu as you've described. Can you say which browser/operating system and version of the extension you're running? v0.3.2 seems to work as expected for me on Linux in Chromium, Edge, and Firefox. Is this from a freshly opened devtools or was there some more setup that puts it in this state?

The Bad Row import expects the pasted input to be JSONL, so the JSON should all be on one line; at the time ElasticSearch's `_source` output matched this format but it looks like nowadays they prettify it so it comes out spread over many lines and just gets ignored. I'll adapt it to keep trying to parse JSON across multiple lines, thanks!

**Comment by k-s-710** [comment]
@jethron  I'm on v0.3.2 on Chrome, I've provided a screen recording below. It's a freshly opened dev tools and have reloaded the frame as well a couple times. 

https://github.com/poplindata/chrome-snowplow-inspector/assets/115262156/34613c32-43a4-4911-9921-06d5b9a8e6d9

Thanks for the note about the source output, I'll see if I can get it to work with one line in the mean time.

**Comment by jethron** [comment]
Thanks @k-s-710 this seems to be MacOS specific. Just waiting for someone on the team on that platform to validate my fix; if all good this will be fixed in the next version.

**Comment by k-s-710** [comment]
Thanks for the confirmation. I also tried the one line source output in the bad rows and it also did not show anything. Also a mac only issue perhaps?
