### ISSUE TITLE
Snowplow inspector crashes

### ISSUE THREAD

**Issue by awoehrl** [poplindata/chrome-snowplow-inspector#72]
Hi,

since a couple of weeks, the inspector crashes when visiting specific pages on our website. The ui becomes totally unresponsive and the only fix is to close web developer tools.

Steps to reproduce:

1. Open Snowplow Inspector
2. Visit any of our article pages: https://www.swp.de/politik/teures-gas_-teurer-strom-zwei-gruende_-weshalb-die-energiekosten-wieder-steigen-koennten-72132927.html
3. Click on any of the paywall offer buttons
4. Inspector UI crashes and it's not possible to navigate between any of the events

Thanks for your help!

**Comment by miike** [comment]
Hi @awoehrl thanks for raising this.

Can you let me know what version of the inspector you are using, what Chrome version and what operating system you are on?

I've been unable to replicate this locally so could you also let me know what order of steps (e.g., paywall offer buttons) to click to try and replicate (or a video would be great too).

Thanks!

**Comment by awoehrl** [comment]
Hi @miike,

thanks for your reply! We are seeing this problem on various machines (that all have the same OS and Chrome version).

Chrome version: 116.0.5845.141
OS: Windows 10 Pro 10.0.19045

This is a short screen recording of the problem:
https://www.loom.com/share/74be2f5410514cef89ad25b840d1dbb0?sid=af7d9450-4d16-4bca-9633-0985fe0af4dd

**Comment by awoehrl** [comment]
Ok, I think I've found the culprit after a couple of days of digging: We were sending a buggy add-to-cart event that attempts to add two contexts. One of the contexts returns as NULL though, which seems to crash the Inspector:

```
{
  total_value: 8,
 currency: "EUR",
 sku: "O_0X2EIODOXG8IQ3DRXU",
 quantity: 1,
 context: [

  null,

    {
      schema: "iglu:com.snowplowanalytics.snowplow.ecommerce/product/jsonschema/1-0-0",
 data: {
        name: "Kennenlernabo",
 id: "O_0X2EIODOXG8IQ3DRXU",
 price: 8,
 brand: "SWP",
 quantity: 1,
 currency: "EUR",
 category: "plus"
      }
    }
  ]
}
```

**Comment by miike** [comment]
Thanks for the additional info as that's a tricky one to reproduce. We'll look at updating the inspector to handle null values in the contexts array.
