### ISSUE TITLE
Extension not showing up in chrome

### ISSUE THREAD

**Issue by funkydunc** [poplindata/chrome-snowplow-inspector#73]
Hi

First of all thank you for creating this helpful extension.

The issue I'm experiencing is that the extension is no longer listed as one of my available tools in Chrome. I have reinstalled Chrome and the extension today.

The screenshow shows that I have the snowplow extension installed and pinned to the toolbar, but it's not available as a tab in my devTools.

![image](https://github.com/poplindata/chrome-snowplow-inspector/assets/25347823/52d2332a-7675-4d5c-998b-8bba7c6102c4)

Thanks in advance for your help.

**Comment by funkydunc** [comment]
I have found the workaround as per https://github.com/poplindata/chrome-snowplow-inspector/issues/49
Visit snowplowanalytics.com first, and then the 'snowplow' dev tools tab is found.

**Comment by miike** [comment]
Thanks @funkydunc for this report. I suspect this may be a different issue due to a [Chrome change](https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4386962) which now prevents dev tools extensions from being loaded on privileged pages (e.g., `chrome://`)
